### ISSUE TITLE
Well question more than issue...

### ISSUE THREAD

**Issue by l0rddarkf0rce** [theNetworkChuck/NetworkChuck#4]
what is running on port 8080. I open a shell to the container and netstat -an shows nothing listening on port 8080. If it is not needed why is there a port forwarder in the startup script?

**Comment by Chemikaze** [comment]
https://youtu.be/dH3DdLy574M
It's how you use Alexa/Home/Siri to automate site blocking.

**Comment by l0rddarkf0rce** [comment]
got it... thanks... startup script modified.
