### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Chef-rox** [theNetworkChuck/NetworkChuck#7]
Hay I'm trying to run this on a PI 4 running ubuntu server 20.04 64bit and I keep getting this error standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by Chef-rox** [comment]
My bad I didn't read the previous issue properly

**Comment by MiChaelinzo** [comment]
> Hay I'm trying to run this on a PI 4 running ubuntu server 20.04 64bit and I keep getting this error standard_init_linux.go:211: exec user process caused "exec format error"

How did you fix it? I have `go:207` I'm also running Raspberry Pi 4 model B but in GNU/Linux 5.4.51-v7l+
OS: Raspberry Pi 4 Model B+ Raspbian GNU/Linux 10 (buster) Linux version 5.4.51+v7l+
Version 5.4.51+v7l+ (don@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22-88-g8460611)) #1333 SMP
Architecture: arm, armv7l
